CREATE TABLE Employee (
id int,
position varchar(255),
gender varchar(255),
marital_status varchar(255),
job_stop int,
absence varchar(255),
absence_days int,
salary int,
city varchar(255),
children_num int,
age int,
has_mentor int,
experience int,
job_start_month int,
layoff_month int,
is_large_family int,
is_retiree int);
